version: '3.9'

services:
    channel-challenge-base-node:
        image: channel-challenge-base-node
        build:
            context: ..
            dockerfile: docker/Dockerfile

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        links:
            - channel-challenge-1
            - channel-challenge-2
        ports:
            - '3050:80'
        networks:
            - app-net

    channel-challenge-1:
        image: channel-challenge-base-node
        expose:
            - '3000'
        networks:
            - app-net
        command: './docker/init.sh'
        environment:
            - FORCE_COLOR=1
        volumes:
            - './../src:/project/src:ro'
            - './../environments/.env:/project/environments/env:ro'
            - './../logs:/project/logs'
        depends_on:
            - mongo-db
            - redis-db

    channel-challenge-2:
        image: channel-challenge-base-node
        expose:
            - '3000'
        networks:
            - app-net
        command: './docker/init.sh'
        environment:
            - FORCE_COLOR=1
        volumes:
            - './../src:/project/src:ro'
            - './../environments/.env:/project/environments/env:ro'
            - './../logs:/project/logs'
        depends_on:
            - mongo-db
            - redis-db

    mongo-db:
        image: mongo
        ports:
            - 27016:27017
        networks:
            - app-net

    redis-db:
        image: redis
        ports:
            - 6378:6379
        networks:
            - app-net

networks:
    app-net:
